apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: smoke-tests
spec:
  inputs:
    resources:
    - name: image
      type: image
    params:
    - name: project
      description: Specify the name of the project being built.
      type: string
    - name: namespace
      description: Specify the namespace you want the pipeline to run in.
      type: string
    - default: googlefu/apic_compiler:v2-amd64
      name: tools-image
      type: string
  steps: 
    - name: health-checks
      env:
        - name: project
          value: $(inputs.params.project)
        - name: namespace
          value: $(inputs.params.namespace)
      image: $(inputs.params.tools-image)
      command: ["/bin/sh"]
      args:
        - -c
        - |
          set e
          pwd
          oc get routes
          projectverb=$project-http

          base_url=$(oc get routes | grep -w $projectverb | cut -f5 -d ' ')
          total_url=${base_url}/micro/inventory
          deployment_name=$(oc get deployments | grep $project | cut -f1 -d ' ')
          status="$(oc rollout status deployment "$deployment_name")"
          pass='successfully rolled out'

          if [[ "$status" == *"$pass"* ]]
          then
            echo "Pods are deployed"
          else
            echo "Pods failed to deploy."
            exit 1
          fi


          if (( $(curl -o /dev/null --silent --head --write-out "%{http_code}" $total_url) != 200 ))
          then
            printf "Server is not serving json properly"
            exit 1
          fi