apiVersion: v1
kind: Secret
metadata:
  name: common-settings
data:
  username: <BASE64 ENCODE USERID FOR ACCESSING CLOUD PAK FOR INTEGRATION>
  password: <BASE64 ENCODE PASSWORD FOR ACCESSING CLOUD PAK FOR INTEGRATION>
  url: <<BASE64 ENCODE URL FOR ICP CONSOLE URL>
  cloudType: <BASE64 ENCODE ("ibmcloud" or "onprem")>
  offlineInstall: <BASE64 ENCODE TRUE OR FALSE>
  fileStorage: <BASE64 ENCODE "nfs" or "csi-cephfs" or "ibmc-file-gold" or "any RWX storage provider">
---
apiVersion: v1
data:
  password: <BASE64_ENCODE(API_KEY)>
  username: <BASE64_ENCODE(GIT_USER_NAME)>
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://<Github Enterprise URL>
  labels:
    serviceAccount: pipeline
  name: git-secret
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  annotations:
    tekton.dev/docker-0: image-registry.openshift-image-registry.svc:5000
type: kubernetes.io/basic-auth
stringData:
  username: <USERID_USED_TO_LOGIN_TO_OPENSHIFT_CLUSTER>
  password: <PASSWORD_TO_LOGIN_TO_OPENSHIFT_CLUSTER>

---
apiVersion: v1
data:
  ARTIFACTORY_ENCRYPT: <base64 encoded bytestring>
kind: Secret
metadata:
  annotations:
    description: Secret to hold the API Key for artifactory so that
      other components can access it
  labels:
    app: artifactory
    app.kubernetes.io/component: tools
    app.kubernetes.io/instance: artifactory
    app.kubernetes.io/name: artifactory
    app.kubernetes.io/part-of: artifactory
    app.kubernetes.io/version: 0.1.3
    chart: tool-config-0.1.3
    group: catalyst-tools
    grouping: garage-cloud-native-toolkit
    release: artifactory
  name: artifactory-access
type: Opaque
