apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: bluecompute-build-and-deploy-pipeline
spec:
  resources:
    - name: git-source-web
      type: git
    - name: docker-image-web
      type: image
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: /workspace/git-source-web
    - name: pathToDockerFile
      description: The path to the dockerfile to build (relative to the context)
      default: Dockerfile
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: k8s/deployment.yaml
    - name: image-name
      description: Url of image repository
    - name: image-tag
      description: Tag to apply to the built image
  tasks:
  - name: build-task
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: pathToDockerFile
        value: "$(params.pathToDockerFile)"
      - name: image-name
        value: "$(params.image-name)"
      - name: image-tag
        value: "$(params.image-tag)"
    resources:
      inputs:
      - name: git-source-web
        resource: git-source-web
      outputs:
      - name: docker-image-web
        resource: docker-image-web
    taskRef:
      name: bluecompute-web-build-task
  - name: deploy-task
    params:
      - name: pathToYamlFile
        value:  "$(params.pathToYamlFile)"
      - name: image-name
        value: "$(params.image-name)"
      - name: image-tag
        value: "$(params.image-tag)"
    resources:
      inputs:
      - name: git-source-web
        resource: git-source-web
      - name: docker-image-web
        resource: docker-image-web
    runAfter:
    - build-task
    taskRef:
      name: bluecompute-web-deploy-task
